
# Generated by Django 3.2.3 on 2021-06-15 17:05



from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetsHometDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommend_Post',
            fields=[
                ('post_num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=30, null=True)),
                ('like_num', models.IntegerField(default=0)),
                ('post_url1', models.CharField(max_length=500, null=True)),
                ('post_url2', models.CharField(max_length=500, null=True)),
                ('post_url3', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe_Cart',
            fields=[
                ('cart_num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('post_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letshometApp.recommend_post')),
                ('post_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_cart_requests_created', to='letshometApp.recommend_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letshometApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Post',
            fields=[
                ('post_num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letshometApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Comment',
            fields=[
                ('comment_num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letshometApp.user')),
                ('post_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letshometApp.review_post')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend_Comment',
            fields=[
                ('comment_num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letshometApp.user')),
                ('post_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letshometApp.recommend_post')),
            ],
        ),
        migrations.CreateModel(
            name='Homet_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('days', models.ImageField(upload_to='')),
                ('subscribe_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letshometApp.subscribe_cart')),
            ],
        ),
    ]
