# Generated by Django 3.2.3 on 2021-05-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letshometApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend_Post',
            fields=[
                ('post_num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('like_num', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe_Cart',
            fields=[
                ('cart_num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('post_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letshometApp.recommend_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letshometApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Post',
            fields=[
                ('post_num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letshometApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Comment',
            fields=[
                ('comment_num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letshometApp.user')),
                ('post_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letshometApp.review_post')),
            ],
        ),
        migrations.AddField(
            model_name='recommend_post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letshometApp.user'),
        ),
        migrations.CreateModel(
            name='Recommend_Comment',
            fields=[
                ('comment_num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letshometApp.user')),
                ('post_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letshometApp.recommend_post')),
            ],
        ),
    ]
