# Generated by Django 3.2.3 on 2021-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letshometApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend_post',
            name='hit_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
