# Generated by Django 3.2.3 on 2021-06-04 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letshometApp', '0003_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend_post',
            name='image',
        ),
        migrations.AddField(
            model_name='recommend_post',
            name='post_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recommend_post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='letshometApp.user'),
        ),
    ]
