# Generated by Django 3.2.3 on 2021-06-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letshometApp', '0004_auto_20210604_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
