# Generated by Django 3.2.3 on 2021-06-04 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letshometApp', '0005_auto_20210604_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe_cart',
            name='title',
        ),
        migrations.AddField(
            model_name='subscribe_cart',
            name='post_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_cart_requests_created', to='letshometApp.recommend_post'),
        ),
    ]
