# Generated by Django 3.2.3 on 2021-06-05 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letshometApp', '0006_auto_20210604_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homet_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('days', models.ImageField(upload_to='')),
                ('subscribe_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letshometApp.subscribe_cart')),
            ],
        ),
    ]
