# Generated by Django 3.2.3 on 2021-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letshometApp', '0007_homet_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend_post',
            old_name='post_url',
            new_name='post_url1',
        ),
        migrations.AddField(
            model_name='recommend_post',
            name='post_url2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recommend_post',
            name='post_url3',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
