# Generated by Django 3.2.3 on 2021-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letshometApp', '0009_alter_recommend_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_post',
            name='like_num',
            field=models.IntegerField(null=True),
        ),
    ]
